name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: "ubuntu-latest"
    env:
      SPIN_VERSION: v2.0.1
    steps:
      - uses: actions/checkout@v2

      - name: Install spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SPIN_VERSION }}

      - name: Test site
        run: |
          cd docs
          ./tests/test-server.sh
